apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-workspace-operator.fullname" . }}
  labels:
    {{- include "kube-workspace-operator.labels" . | nindent 4 }}
type: Opaque
data:
  config.json: {{ .Values.config | toJson | b64enc | quote }}

