---
name: Checks

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rust:
    strategy:
      matrix:
        rust-channel: [stable, nightly]
        python-version: ["3.8"]
    runs-on: ubuntu-latest
    env:
      RUST_VERSION: ${{ matrix.rust-channel }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up rustup
        run: "rustup update $RUST_VERSION && rustup default $RUST_VERSION && rustup component add clippy && rustup component add rustfmt"

      - name: rustc info
        run: "rustup run $RUST_VERSION rustc --version && rustup run stable cargo --version"
      
      - name: Operator
        run: "rustup run $RUST_VERSION cargo xtask ci-rust"

      - name: Install Python dependencies
        run: "pip install black pylint mypy"

      - name: CLI
        run: "rustup run stable cargo xtask ci-cli"
