---
name: Checks

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  pull_request:
    branches: [main]

jobs:
  rust:
    strategy:
      matrix:
        rust: [stable, nightly]
    runs-on: ubuntu-latest
    env:
      RUST_VERSION: ${{ matrix.rust }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up rustup
        run: "rustup default $RUST_VERSION && rustup component add clippy"

      - name: rustc info
        run: "rustup run $RUST_VERSION rustc --version && rustup run stable cargo --version"
      
      - name: cargo test
        run: "rustup run stable cargo test"

      - name: lint - cargo clippy
        run: "RUSTFLAGS=\"-D warnings\" rustup run $RUST_VERSION cargo clippy"

  cli:
    name: CLI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup
        run: pip install black pylint mypy 
      
      - name: "Lint: mypy"
        run: mypy --strict workspaces.py
      - name: "Lint: black (formatting)"
        run: black --check workspaces.py
      - name: "Lint: pylint"
        run: pylint workspaces.py
